---
- name: Provision macOS for development
  hosts: all
  connection: local
  tasks:
  - name: Install VS code as editor
    homebrew_cask:
      name: visual-studio-code
      state: present
  - name: Install pyenv, for multiple python versions
    homebrew:
      name: pyenv
      state: present
  - name: Install latest python version
    homebrew:
      name: pyenv
      state: present
  - name: Add a line to a file if the file does not exist, without passing regexp
    lineinfile:
      path: ~/.zshrc
      line: eval "$(pyenv init -)"
      create: yes